import numpy as np 
a=np.array([0,30,45,60,90])
print(np.cos(a))
print(np.arccos(a))
print(np.sin(a))
print(np.arcsin(a))
print(np.tan(a))
print(np.arctan(a))
print('\n')
b=np.array([1.5,2.7,4.65,8.88])
print(np.around(b))
print(np.floor(b))
print(np.ceil(b))